version: '3.8'
services:
  db:
    image: dhi.io/postgres:15-alpine3.22
    container_name: taskdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-taskuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-taskpass}
      POSTGRES_DB: ${POSTGRES_DB:-taskdb}
    volumes:
      # The DHI postgres image does not use a versioned subpath like the normal image from the hub so I adapted it 
      - postgres_data:/var/lib/postgresql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-taskuser} -d ${POSTGRES_DB:-taskdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: dhi.io/redis:7-debian13
    container_name: taskcache
    # Added the password authentication
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-taskredis}"]
    networks:
      - backend
    healthcheck:
      # Changed the test to consider the password setup
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-taskredis}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    # Added the name for the image
    image: dhi-taskapi:latest
    container_name: taskapi
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-taskuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-taskpass}
      POSTGRES_DB: ${POSTGRES_DB:-taskdb}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-taskredis}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: dhi.io/nginx:1.29.6-alpine3.23
    container_name: taskproxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      api:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "kill -0 $(cat /var/run/nginx.pid) || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
